worker_processes auto;
error_log stderr info;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
    use epoll;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    client_max_body_size 10m;

    upstream waf_api_backend {
        server wirefall-api:8001;
    }

    upstream waf_logs_backend {
        server wirefall-logs:8002;
    }

    server {
        listen 80;
        server_name localhost;
        charset utf-8;

        location /dashboard/ {
            alias /var/www/dashboard/;
            index index.html;
        }

        location /health {
            proxy_pass http://waf_api_backend/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /analyze {
            proxy_pass http://waf_api_backend/analyze;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /set-mode/ {
            proxy_pass http://waf_api_backend/set-mode/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /pass-request {
            proxy_pass http://waf_api_backend/pass-request;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /simulate/ {
            proxy_pass http://waf_api_backend/simulate/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /rules {
            proxy_pass http://waf_api_backend/rules;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ws/logs {
            proxy_pass http://waf_api_backend/ws/logs;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location /logs {
            proxy_pass http://waf_logs_backend/logs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            access_by_lua_file /etc/nginx/lua/waf_chain.lua;
            proxy_pass http://waf_api_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
