FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn pymongo python-dotenv pydantic

COPY api/ api/

EXPOSE 8002

CMD ["uvicorn", "api.logs_service:app", "--host", "0.0.0.0", "--port", "8002"]
